---
# tasks file for nginx

- name: Install Nginx Web Server on Debian Family
  apt:
    name: nginx
    state: latest
    update_cache: true

- name: Apply Page Template
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify:
      - nginx systemd

- name: restart nginx
  service:
    name: nginx
    state: restarted
